title: The Open Toolbox
url: https://the.opentoolbox.online
baseurl: ""
favicon: https://i.ibb.co/NW81dVJ/The-Open-Toolbox-Cropped.gif
logo: https://i.ibb.co/NW81dVJ/The-Open-Toolbox-Cropped.gif
lang: it

repository: opentoolbox/template

incremental: true # Still experimental as of v4.2.0, disable if it leads to build not updating

show_downloads: false

show_sidebar: true

permalink: /posts/:title

collaboration_links:
  issues: https://github.com/opentoolbox/template/issues
  pull_requests: https://github.com/opentoolbox/template/pulls
  discussions: https://github.com/opentoolbox/template/discussions

markdown: kramdown
fenced_code_blocks: true
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'highlight'

footer_menu: footer_menu
fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Set plugins here to make it compatible with GitHub pages.
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-environment-variables
  - jekyll-mentions
  - jekyll-target-blank

jekyll-mentions:
  base_url: https://github.com

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

defaults:
  - scope:
      path: ""
    values:
      layout: page
      author: community
      image: https://i.ibb.co/hLw08Wj/The-Open-Toolbox.gif
      hero_image: 
      hero_height: is-medium
      hero_darken: true
  - scope:
      path: "resources/*"
    values:
      layout: resource
      show_sidebar: false
      menubar: main_menu
  - scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: true
      banner_with_image: true
      image: 
      author: community
